🧩 :: (#119) 기업지원내역 상세조회 api
Team-Return/JOBIS-DSM-BE pull request #124
Opened 2023-02-18 02:18 UTC by gilgeunwoo

### 해당 이슈⚡️

- close #119 

### 변경사항✅

- 기업지원내역 상세조회 api 추가

2023-02-20 05:16 UTC, tedsoftj1123 requested changes

2023-02-20 05:16 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +
생각해보니 이건 리스트로 반환되면 안되니까 applicationAttatchments를 fetchJoing하고 서비스단에서 대충 가공해서 만들어주는게 더 좋을 것 같아요

2023-02-20 05:16 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +
메소드명은 queryApplicationById가 어떤가요?

2023-02-23 03:29 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +
이거 근데 디자인따라서 api를 변경해야될거같아요 세부조회랑 리스트조회로 나누지말고 한번에 리스트로 다 줘야될거같아서 그렇게 수정하겠습니다.

2023-02-23 04:07 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +
보니까 선생님단에서는 따로 조회하긴 하네요 둘다 만들게요

2023-03-02 03:11 UTC, tedsoftj1123 requested changes

2023-03-02 03:11 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +                );
여기 메소드들 내용이 같은 거 같은데 where문을 BooleanExpression써서 조건문 함수로 만들어서 사용하면 좋을것 같아요
https://github.com/Team-Return/JOBIS-DSM-BE/blob/main/src/main/java/com/example/jobis/domain/recruit/domain/repository/RecruitmentRepository.java
예시

2023-03-02 03:11 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/student/domain/Student.java
> +
학번에 대한 내용을 또 저장하면 중복이 되니 Student클래스에다 도메인로직으로 분리해서 getGcn이런 메소드 만들어서 사용하면 좋을 것 같아요, 근데 지금 학년이 enum이라서 이거 그냥 int로 바꿀지도 한번 생각해봐야겠네요

2023-03-02 03:11 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +import static com.querydsl.core.group.GroupBy.*;
wildcard import는 지양하는게 좋습니다 무엇을 import했는지 코드상으로 확인하기 어려워요

2023-03-02 03:11 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationListResponse.java
> +    private final List<String> urlList;
여기 urlList보다 attatchmentUrlList어떤가요?

2023-03-02 05:15 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryApplicationListResponse.java
> +    private final LocalDateTime createdAt;
그렇다면 제거하겠습니다

2023-03-02 05:16 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +                );
넵

2023-03-02 05:18 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +import static com.querydsl.core.group.GroupBy.*;
수정하겠습니다

2023-03-02 05:19 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/service/QueryApplicationListService.java
> +public class QueryApplicationListService {
list말고 써야하는 표현이 무엇이있을까요?

2023-03-02 06:18 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryApplicationListResponse.java
> +    private final LocalDateTime createdAt;
지금 바꾸려고 보니까 createdAt은 LocalDateTime 형식이라 LocalDate와 맞지않네요

2023-03-03 05:29 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryCompanyApplicationListResponse.java
> +    private final LocalDateTime createdAt;
여기 LocalDate로 바꿔주세용

2023-03-03 05:29 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryTeacherApplicationListResponse.java
> +    private final LocalDateTime createdAt;
동일합니다

2023-03-03 05:29 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/vo/QueryApplicationVO.java
> +    private final LocalDateTime createdAt;
동일합니닫

2023-03-03 05:29 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/service/QueryCompanyApplicationListService.java
> +public class QueryCompanyApplicationListService {
여기그냥 Query~~ApplicationsService로하는게 어떨지

2023-03-03 05:29 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/service/QueryStudentApplicationListService.java
> +public class QueryStudentApplicationListService {
동일합니다

2023-03-03 08:21 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryTeacherApplicationsResponse.java
> +}
선생님이 볼때 회사 이름도 표시되면 좋을 것 같아요

2023-03-03 08:21 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
> +            @RequestParam(value = "recruitment-id", required = false) UUID recruitmentId,
전체 조회를 하는데 recruitment-id가 필요할까요?

2023-03-03 08:21 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationsResponse.java
> +    private final String student;
학생이 자기 내역을 조회하는데 학생의 정보를 가져올 필요가 있을까요?

2023-03-03 08:21 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/QueryTeacherApplicationsResponse.java
> +}
TeacherQueryApplications는 어떤가요? 뭔가 선생님이 지원한 내역조회라는 느낌이 듭니다

2023-03-03 08:21 UTC, tedsoftj1123 commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +    public List<QueryApplicationVO> queryApplicationByConditions(UUID recruitmentId, UUID studentId, ApplicationStatus neApplicationStatus, ApplicationStatus eqApplicationStatus, Integer year, String
파라미터가 너무 많은 것 같으니 요청객체를 따로 만드는건 어떤가요?

2023-03-03 08:24 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/controller/ApplicationController.java
> +            @RequestParam(value = "recruitment-id", required = false) UUID recruitmentId,
의뢰서마다의 학생을 보는 디자인때문에 만들어 놓았습니다.

2023-03-03 08:25 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/controller/dto/response/StudentApplicationsResponse.java
> +    private final String student;
빼겠습니다

2023-03-03 08:25 UTC, gilgeunwoo commented on src/main/java/com/example/jobis/domain/application/domain/repository/ApplicationRepository.java
> +    public List<QueryApplicationVO> queryApplicationByConditions(UUID recruitmentId, UUID studentId, ApplicationStatus neApplicationStatus, ApplicationStatus eqApplicationStatus, Integer year, String
넵

2023-03-03 10:51 UTC, tedsoftj1123 submitted a review, later dismissed
수고하셨습니😎

2023-03-03 10:57 UTC, tedsoftj1123 approved these changes
😯

2023-03-03 10:58 UTC, merged