🔗 :: (#154) 비밀번호 변경 api
Team-Return/JOBIS-DSM-BE pull request #158
Opened 2023-03-22 12:49 UTC by gilgeunwoo

### PR 설명 🔎
- POST /students/code/password
    - send password auth code
- PATCH /students/password
    - update password

### 주요 변경사항 ✅
- SendPasswordAuthCodeService
- UpdatePasswordService

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #154

2023-03-23 01:25 UTC, tedsoftj1123 requested changes

2023-03-23 06:28 UTC, alsdl0629 commented on src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
>          }
p3; request로 받아올 때 검증하는 데 여기서 또 검증 안 해도 되지 않나요?

2023-03-23 08:13 UTC, alsdl0629 commented on src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
> +        if (!studentFacade.existsEmail(request.getEmail())) {
p3; existsEmail 메서드 userFacade로 옮기는 건 어떤가요?

2023-03-23 08:13 UTC, alsdl0629 commented on src/main/java/team/returm/jobis/domain/auth/presentation/AuthController.java
> +    @PatchMapping("/code")
p2; 검증하는 api인데 get으로 변경하는 게 맞을 것 같아요

2023-03-23 08:18 UTC, alsdl0629 commented on src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
> +    }
p4; 이 부분 service로 옮기는 건 어떨까요?

2023-03-23 08:20 UTC, alsdl0629 approved these changes

2023-03-24 01:31 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
> +    }
코드 짤때도 고민을 해봤는데 service에 있는게 맞을까요?

2023-03-24 01:54 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
> +        if (!studentFacade.existsEmail(request.getEmail())) {
다른 pr에서 하셨네용

2023-03-24 05:15 UTC, tedsoftj1123 requested changes

2023-03-24 05:15 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/student/service/UpdateStudentPasswordService.java
> +        student.updatePassword(passwordEncoder.encode(request.getPassword()));
p3; 여기 student랑 user랑 통일해야될것 같아요

2023-03-24 05:15 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/student/presentation/dto/request/UpdatePasswordRequest.java
> +    private String password;
p3; 여기 notblank 붙여주세요

2023-03-24 05:15 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/auth/facade/AuthCodeFacade.java
> +
p4; 여기 들여쓰기 없애주세용

2023-03-24 05:15 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/auth/service/SendAuthCodeService.java
> +}
p3; sendMail이라는 메소드에 너무 많은 책임이 있는것 같아요 AuthCode를 save하는 부분은 service단으로 분리하는게 좋을 것 같아요

2023-03-24 07:58 UTC, alsdl0629 commented on src/main/java/team/returm/jobis/domain/auth/presentation/AuthController.java
> +    @PatchMapping("/code")
넵

2023-03-29 10:02 UTC, tedsoftj1123 approved these changes
수고하셨습니다😺

2023-03-29 10:16 UTC, merged