Feat/(#155)query filter recruit company
Team-Return/JOBIS-DSM-BE pull request #159
Opened 2023-03-23 06:21 UTC by gilgeunwoo

### PR 설명 🔎
- 학생 모집의뢰서 조회시 기술코드로 검색 필터 추가
- 학생 회사 조회시 기술코드로 검색 필터 추가

### 주요 변경사항 ✅
- StudentQueryCompaniesService
- StudentQueryRecruitmentsService

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #155

2023-03-23 07:10 UTC, tedsoftj1123 requested changes

2023-03-23 07:10 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
> +            @RequestParam(value = "keyword", required = false) List<String> keywords
p3; 사용자의 입장에서 딱히 여러개의 기술을 입력해서 조회하는 기능을 사용하지 않을거라고  생각하는데 어떻게 생각하시나요?

2023-03-23 07:10 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
> +        return keywords == null ? null : recruitment.recruitAreaList.any().codeList.any().codeKeyword.in(keywords);
p2; =연산을 사용하면 사용자가 코드를 정확히 똑같이 입력해야되기 때문에 많이 불편할것 같아요, like를 상용하는 쿼리로 수정되면 좋을 것 같아요

2023-03-23 07:10 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
> +        return keywords == null ? null : recruitment.recruitAreaList.any().codeList.any().codeKeyword.in(keywords);
p2; 그리고 이렇게되면 직무코드 무관하고 다 비교해서 따로 JOB코드만 검색하는 조건을 추가해야될것 같아요

2023-03-23 08:20 UTC, alsdl0629 approved these changes

2023-03-24 00:52 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
> +        return keywords == null ? null : recruitment.recruitAreaList.any().codeList.any().codeKeyword.in(keywords);
제가 생각한건 사용자가 직접 입력이 아니라 키워드들은 정해져있고 프론트에서 정확히 정해진 기술코드들을 전송해주는거로 생각하고 있었습니다.

2023-03-24 00:55 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/recruitment/presentation/RecruitController.java
> +            @RequestParam(value = "keyword", required = false) List<String> keywords
여러개가 있는게 좋을거 같아요. 다른 채용사이트에서도 기술스택을 여러가지 입력하여 조회하는 기능이 있어요.

2023-03-24 00:56 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
> +            @RequestParam(value = "keyword", required = false)List<String> keywords
직무 키워드로 조회하는 건 어떨까요?

2023-03-24 03:17 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
> +            @RequestParam(value = "keyword", required = false)List<String> keywords
회사 조회할때 직무로 조회하는건 모집직무니까 모집의뢰서에 해당되는것 같아요, 사업분야를 사용하면 좋을것 같긴한데.. 현제 사업분야에 대한 컬럼이 없어서 고민이네요

2023-03-24 03:21 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
> +            @RequestParam(value = "keyword", required = false)List<String> keywords
사업분야 칼럼이 필요하긴 할것같네요 일단 그럼 키워드 조회는 제거하겠습니다.

2023-03-24 03:22 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
> +        return keywords == null ? null : recruitment.recruitAreaList.any().codeList.any().codeKeyword.in(keywords);
기능명세가좀 부실한 느낌이 있어서 저 뿐만 아니라 다른 분야들도 좀 했갈릴거 같네요.. 모든 분야 통틀어서 문서화를 확실히 하는게 좋을것 같아요

2023-03-25 07:03 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/recruitment/domain/repository/RecruitmentRepository.java
> +        return keywords == null ? null : recruitment.recruitAreaList.any().codeList.any().codeKeyword.in(keywords);
확실히 부실하긴 해서 한번 회의를 통해 문서화를 확실하게 할 필요가 있을거 같아요

2023-04-05 07:49 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
> +                )
p3; 이거 줄바꿈 없애주세요

2023-04-05 07:49 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/code/domain/repository/CodeRepository.java
> +        }
p2; 이거 null체크 안해줘도 됩니다.

2023-04-05 23:26 UTC, tedsoftj1123 approved these changes

2023-04-06 07:23 UTC, merged