⚒️ :: (#160) 이메일 중복 컬럼 제거
Team-Return/JOBIS-DSM-BE pull request #161
Opened 2023-03-23 14:19 UTC by alsdl0629

### PR 설명 🔎
- 이메일 중복 컬럼 제거

### 주요 변경사항 ✅
- Student Entity email 컬럼 삭제

- [] 로컬 테스트가 오류 없이 작동했나요?

close #160

2023-03-24 01:38 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/user/facade/UserFacade.java
> +    public boolean existsEmail(String accountId) {
p4; existsAccountId가 더 좋을것 같아요

2023-03-24 03:20 UTC, tedsoftj1123 requested changes

2023-03-24 03:20 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/user/domain/User.java
> +    @Column(columnDefinition = "VARCHAR(30)")
p1; 이거 인코딩해서 들어가면 60글자라서 500터질것 같아요

2023-03-24 05:17 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/user/domain/User.java
> +    @Column(columnDefinition = "VARCHAR(30)")
왜 비밀번호가 VARCHAR야

2023-03-24 13:55 UTC, tedsoftj1123 approved these changes
수고하셨습니다😺

2023-03-25 07:38 UTC, gilgeunwoo approved these changes
👍

2023-03-27 11:26 UTC, merged