🔗 :: (#197) 모집의뢰서 조회시 지원자와 지원요청을 따로 반환
Team-return/JOBIS-DSM-BE pull request #200
Opened 2023-04-13 07:23 UTC by gilgeunwoo

### PR 설명 🔎
- 모집의뢰서 조회시 지원자와 지원요청을 따로 반환하도록 변경

### 주요 변경사항 ✅
- Recruitment
- RecruitmentRepository
- ChangeApplicationsStatusService

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #197

2023-04-16 06:11 UTC, tedsoftj1123 requested changes

2023-04-16 06:11 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/recruitment/domain/Recruitment.java
> +    private Integer applicationApprovedCount;
p1; 이거 지원정보가 이렇게 될바에는 그냥 join하는게 편할거같은게 이러면 application이 변경됨에 따라 이 컬럼을 계속 바꿔줘야되서 너무 의존적이게 될것 같아요 1개였을때는 단순했는데 지원요청이라던지 승인될때마다 이거 변경해줘야되는거면 좀 붎편할것 같네요 로직도 꼬일수도 있어서..

2023-04-17 07:46 UTC, alsdl0629 approved these changes

2023-04-17 13:12 UTC, tedsoftj1123 approved these changes

2023-04-17 13:42 UTC, merged