🔗 :: (#208) 현장실습 날짜 변경 api
Team-return/JOBIS-DSM-BE pull request #212
Opened 2023-04-19 11:20 UTC by alsdl0629

### PR 설명 🔎
- 현장실습 날짜 변경 api

### 주요 변경사항 ✅
- ChangeFieldTrainDateServuce

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #211

2023-04-19 14:00 UTC, tedsoftj1123 requested changes

2023-04-19 14:00 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
> +    public void changeFieldTrainDate(LocalDate startDate, LocalDate endDate, List<Application> applications) {
p3; update라는 표현은 어떤가요?

2023-04-20 05:46 UTC, gilgeunwoo approved these changes

2023-04-21 01:12 UTC, tedsoftj1123 approved these changes

2023-04-21 01:12 UTC, tedsoftj1123 commented
코드스멜확인점

2023-04-21 02:54 UTC, merged