🔗 :: (#213) 근로계약 날짜 변경 api
Team-return/JOBIS-DSM-BE pull request #214
Opened 2023-04-19 14:27 UTC by alsdl0629

### PR 설명 🔎
- 근로계약 날짜 변경 api

### 주요 변경사항 ✅
- ChangeContractDateService

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #213

2023-04-20 01:29 UTC, gilgeunwoo requested changes

2023-04-20 01:29 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceRepository.java
> +                .where(acceptance.in(acceptances))
p2; 이거 id.in()으로 해서 acceptances를 조회하지 않고 바로 수정쿼리 날리는거는 어떤가용

2023-04-20 03:16 UTC, tedsoftj1123 approved these changes

2023-04-20 03:16 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/acceptance/domain/repository/AcceptanceJpaRepository.java
> +    List<Acceptance> queryByIdIn(List<Long> ids);
find ^^

2023-04-23 13:21 UTC, gilgeunwoo approved these changes

2023-04-23 13:37 UTC, merged