🔗 :: (#220) 면접 후기 테이블 추가
Team-return/JOBIS-DSM-BE pull request #222
Opened 2023-05-01 10:20 UTC by alsdl0629

### PR 설명 🔎
- Review 도메인 세팅

### 주요 변경사항 ✅
- Review Entity
- Review Repository

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #220

2023-05-01 23:35 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/review/domain/Review.java
> +    private String studentGcn;
p3; 학번은 4자 아닌가요?

2023-05-01 23:37 UTC, gilgeunwoo requested changes

2023-05-01 23:37 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/review/domain/enums/ReviewType.java
> +    PRACTICE_REVIEW,
p2; 이거 FIELD_TRAIN_REVIEW가 좋을거같아요

2023-05-02 01:39 UTC, tedsoftj1123 requested changes

2023-05-02 01:39 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/review/domain/Review.java
> +    @Column(columnDefinition = "VARCHAR(16)")
p1; @Enumerated

2023-05-02 01:41 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/review/domain/Review.java
> +    private ReviewType reviewType;
p3; 얘 그냥 type쓰는게 좋을 것 같아요

2023-05-02 04:23 UTC, gilgeunwoo approved these changes
👍

2023-05-02 04:33 UTC, tedsoftj1123 approved these changes

2023-05-02 07:57 UTC, merged