🔗 :: (#228) 선생님 회사 조회 api
Team-return/JOBIS-DSM-BE pull request #229
Opened 2023-05-02 06:29 UTC by gilgeunwoo

### PR 설명 🔎
- 선생님이 등록페이지에서 사용할 회사 조회 api

### 주요 변경사항 ✅
- TeacherQueryCompaniesService

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #228

2023-05-02 08:11 UTC, alsdl0629 approved these changes

2023-05-03 07:16 UTC, tedsoftj1123 requested changes
소나클라우드 한번 확인해줏에ㅛㅇ

2023-05-03 07:16 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
> +                .leftJoin(company.recruitmentList, recruitment)
p2; 여기 `.leftJoin(recruitment)`으로 사용해도 될 것 같습니다

2023-05-03 07:16 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/company/domain/repository/CompanyRepository.java
> +    }
p3; 쿼리로는 like로 나가긴 하는데 구현상 어쩔 수 없이 사용한거니까 그냥 eqRegion으로 사용하는것은 어떨까요?

2023-05-03 07:16 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/global/util/StringUtil.java
> +
p3; 이건 StringUtil에 있기에는 너무 Company도메인용 메서드인것 같아요

2023-05-03 07:16 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/company/presentation/CompanyController.java
> +            @RequestParam(value = "company_name", required = false) String companyName,
p3; 앞에 company는 없어도 되지 않을까요?

2023-05-03 13:56 UTC, tedsoftj1123 approved these changes
😺

2023-05-04 03:03 UTC, merged