🔗 :: (#230) 학생 메인페이지 api
Team-return/JOBIS-DSM-BE pull request #232
Opened 2023-05-02 10:05 UTC by gilgeunwoo

### PR 설명 🔎
- 학생 메인페이지 api입니다.

### 주요 변경사항 ✅
- StudentMainPageService

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #230

2023-05-03 10:55 UTC, alsdl0629 approved these changes

2023-05-05 03:37 UTC, tedsoftj1123 requested changes

2023-05-05 03:37 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
> +                .on(passedApplication.applicationStatus.eq(ApplicationStatus.PASS))
p1; 이렇게 되면 한 학생의 총 합격수와 지원수를 가져오지 않을까요?

2023-05-07 12:22 UTC, gilgeunwoo commented on src/main/java/team/returm/jobis/domain/application/domain/repository/ApplicationRepository.java
> +                .on(passedApplication.applicationStatus.eq(ApplicationStatus.PASS))
where조건으로 student를 식별하지 않기때문에 전체 학생으로 됩니다.

2023-05-09 06:33 UTC, tedsoftj1123 approved these changes

2023-05-09 06:54 UTC, merged