🔗 :: (#265) 중복 예외처리
Team-return/JOBIS-DSM-BE pull request #266
Opened 2023-05-17 08:13 UTC by alsdl0629

### PR 설명 🔎

- 후기 등록 중복 예외처리
### 주요 변경사항 ✅

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #

2023-05-17 14:05 UTC, gilgeunwoo requested changes

2023-05-18 00:45 UTC, gilgeunwoo approved these changes

2023-05-18 00:52 UTC, tedsoftj1123 commented on src/main/java/team/returm/jobis/domain/review/service/CreateReviewService.java
> +            throw ReviewAlreadyExistsException.EXCEPTION;
p3; 얘는 굳이 분리할 필요가 없어보이는디

2023-05-19 09:48 UTC, tedsoftj1123 approved these changes

2023-05-19 09:56 UTC, merged