🔗 :: (#403) slack webhook 연동 기능 추가
Team-return/JOBIS-DSM-BE pull request #404
Opened 2023-08-31 03:20 UTC by alsdl0629

### PR 설명 🔎

- slack에 버그 제보와 예외발생 한 것들을 이벤트를 사용해서 슬랙으로 메세지를 보냄
- Bugreport에 Student 추가
- SesPort 이름이 추상적이지 않아서 변경함

### 주요 변경사항 ✅

- SlackAdapter
- 버그 제보
<img width="504" alt="스크린샷 2023-08-31 오후 12 19 38" src="https://github.com/Team-return/JOBIS-DSM-BE/assets/103026813/510aaaa1-71f3-48d9-bed5-e67f8b31ab74">

- 예외 발생
<img width="672" alt="스크린샷 2023-08-31 오후 12 20 39" src="https://github.com/Team-return/JOBIS-DSM-BE/assets/103026813/fd8dacd9-879b-447f-af9b-6857938deff1">

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #403

2023-08-31 08:28 UTC, Tmdhoon2 requested changes

2023-08-31 08:28 UTC, Tmdhoon2 commented on jobis-application/src/main/java/team/retum/jobis/domain/auth/usecase/SendAuthCodeUseCase.java
> +    private final SendEmailPort sesPort;
필드 이름 sesPort -> sendEmailPort 로 변경해주세요

2023-08-31 08:28 UTC, Tmdhoon2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/slack/SlackConfig.java
> +    public SlackApi slackApi() {
slackApiProvider() 어떰

2023-08-31 08:28 UTC, Tmdhoon2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/slack/SlackAdapter.java
> +                List.of(
list를 변수로 빼면 가독성이 좋아질 것 같아요

2023-08-31 08:28 UTC, Tmdhoon2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/slack/SlackAdapter.java
> +                    List.of(
여기도 list를 변수로 빼면 가독성이 좋아질 것 같아요

2023-09-01 01:12 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/common/spi/SendExceptionInfoPort.java
> +}
이렇게 직접 slack api를 호출하는 포트를 application layer에 두면 추상화가 되어있지만 이벤트를 사용하는 이유가 없어질것 같아요 application에서는 이벤트 발행만 해야되는게 맞는것 같습니다.

2023-09-01 01:12 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/domain/bug/spi/SendBugReportPort.java
> +}
위와 동일합니다.

2023-09-01 01:12 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/common/spi/PublishExceptionPort.java
> +}
이 메소드를 사용하기 위해 application으로 HttpServletReqeust 객체를 보낼 일이 없을 것 같고 application layer의 책임에 어긋나는것 같으니 이건 infra 모듈에 위치하는게 어떨까요?

2023-09-01 01:12 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/slack/SlackAdapter.java
> +    }
생각해보니 이거 아짜피 이벤트로만 실행되는데 굳이 비동기로 처리될 필요가 있을까요?

2023-09-01 05:58 UTC, tedsoftj1123 approved these changes

2023-09-01 06:21 UTC, gilgeunwoo approved these changes

2023-09-01 06:21 UTC, Tmdhoon2 approved these changes

2023-09-02 08:47 UTC, merged