🧩 :: (#417) 학생 모집의뢰서, 기업 리스트 조회 limit 수정
Team-return/JOBIS-DSM-BE pull request #418
Opened 2023-09-14 04:20 UTC by alsdl0629

### PR 설명 🔎

- 클라 요구로 limit 12로 변경

### 주요 변경사항 ✅

- 
- 

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #417

2023-09-15 06:46 UTC, gilgeunwoo approved these changes

2023-09-15 06:47 UTC, gilgeunwoo requested changes
이거 모집의뢰서부분도 바꿔달라고 했었습니당

2023-09-15 13:50 UTC, gilgeunwoo approved these changes

2023-09-16 09:11 UTC, tedsoftj1123 approved these changes

2023-09-16 13:13 UTC, merged