🔗 :: (#471) 재지원 api
Team-return/JOBIS-DSM-BE pull request #478
Opened 2023-11-28 15:05 UTC by gilgeunwoo

### PR 설명 🔎

- 재지원 api 만들었어용

### 주요 변경사항 ✅

- RecreateApplicationUseCase

- [X] 로컬 테스트가 오류 없이 작동했나요?

close #471

2023-11-29 10:01 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/QueryRejectionReasonUseCase.java
> +        return new QueryRejectionReasonResponse(application.getRejectionReason());
상태가 REJECT아닐 떄 예외처리가 필요할듯합니다

2023-11-29 10:03 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/RecreateApplicationUseCase.java
> +        }
checkApplicationStatus 도메인로직 활용하면 좋을 것 같습니다

2023-11-29 11:13 UTC, alsdl0629 approved these changes

2023-12-02 07:02 UTC, tedsoftj1123 requested changes

2023-12-02 07:02 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/domain/application/model/Application.java
> +        if (List.of(baseStatuses).contains(requestedStatus)) {
이거 이렇게 바꿔버리면 기존에 이 메소드 사용하고 있는 서비스들이 거꾸로 동작할거같은디

2023-12-03 05:39 UTC, Tmdhoon2 commented
혹시 언제 머지되나요

2023-12-03 12:21 UTC, merged