🧩 :: (#502) banner entity mapping
Team-return/JOBIS-DSM-BE pull request #507
Opened 2024-01-21 10:01 UTC by ilyoil2

### PR 설명 🔎

- banner entity mapping
- 

### 주요 변경사항 ✅

- 
- 

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #504

2024-01-21 10:27 UTC, geunoo requested changes

2024-01-21 10:27 UTC, geunoo commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +
메서드는 공백 없이 시작합니다

2024-01-21 10:27 UTC, geunoo commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/repository/BannerJpaRepository.java
> +public interface BannerJpaRepository extends CrudRepository<Banner, Long> {
BannerEntity

2024-01-21 11:24 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
엔티티에 생성전략을 IDENTITY로 설정했으면 id 필드는 초기화하지 않아도 되는데 도메인 모델을 엔티티로 변환할때 위 코드처럼 초기화해주는 이유가 궁금함돠

2024-01-22 08:33 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
IDENTITY로 설정해주었으면 자동으로 id가 늘어날텐데 왜 이렇게 했을까요.. 도메인과 엔티티의 id 값을 한 번 더 동일하게 설정해주려고 하는게 아닐까요?

2024-01-22 12:25 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
엔티티를 업데이트를 하는 경우를 생각해보면 도움이 될거같아용

2024-01-22 12:35 UTC, tedsoftj1123 commented
<img width="310" alt="image" src="https://github.com/Team-return/JOBIS-DSM-BE/assets/52336493/d42502c2-b8a6-4358-b02f-3379476f92fd">
  
커멘트 고치고 저 재활용버튼처럼 생긴거 눌러주면 우리한테 알람와서 더 빨리 볼 수 있음

2024-01-23 06:31 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
엔티티를 업데이트 할 때 필드의 값을 변경하는게 아니라 새로운 엔티티를 만드는 방식으로 되어있어서 id값이 증가되니까 domain과 id값을 같게 하려고 이렇게 설정하는 것 같은데 맞을까요?

2024-01-23 09:52 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
굿👍
새로 생성된 엔티티는 persist, 이미 영속성 컨텍스트에서 관리되던 엔티티면 merge를 해야되는데 너말대로 mapper를 사용하면 도메인 모델을 엔티티 객체로 변환할때 무조건 새 객체가 되니까 기존에 db에 있던 값을 불러오고 수정한 다음 save를 하면 persist로 동작하기 때문에 update가 아닌 insert쿼리가 나감, 그래서 update동작시 문제가 됨
(새 객체인지 판단하는법: https://hyewoncc.github.io/jpa-is-new/)

2024-01-23 09:53 UTC, tedsoftj1123 approved these changes
근우 코멘트 고친거 반영안된거같은디 일단 approve해놓음

2024-01-23 13:31 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/banner/mapper/BannerMapper.java
> +                .id(domain.getId())
넵

2024-01-26 04:13 UTC, geunoo approved these changes

2024-02-11 09:49 UTC, merged