🔗 :: (#516) 회사 user조인 제거
Team-return/JOBIS-DSM-BE pull request #517
Opened 2024-02-19 07:57 UTC by geunoo

### PR 설명 🔎

-  회사 user조인 제거
- 관련 api 수정

### 주요 변경사항 ✅

- companyentity
- registerCompanyUseCase
- ApplyRecruitmentUseCase

- [ ] 로컬 테스트가 오류 없이 작동했나요?

close #516

2024-02-19 10:23 UTC, tedsoftj1123 approved these changes

2024-02-19 10:23 UTC, tedsoftj1123 commented on jobis-application/src/main/java/team/retum/jobis/domain/company/usecase/RegisterCompanyUseCase.java
> +    public void execute(RegisterCompanyRequest request) {
ID 반환해주는게 좋을듯?

2024-02-19 13:10 UTC, alsdl0629 approved these changes

2024-02-20 07:55 UTC, tedsoftj1123 reviewed
ddl 날리고머지해주세요

2024-02-20 07:57 UTC, tedsoftj1123 requested changes
생각해보니 SecurityConfig도 고쳐야될듯

2024-02-21 00:13 UTC, geunoo commented
야 저거 그냥 Changes requested날리면 resolve를 못하는데?

2024-02-21 04:44 UTC, tedsoftj1123 approved these changes

2024-02-21 06:30 UTC, merged