🔗 :: (#628) code, file 패키지 리펙토링
Team-return/JOBIS-DSM-BE pull request #631
Opened 2024-04-11 07:06 UTC by 4mjeo

## 작업 내용 설명
- 공지사항 작성 후 알림 송신 api

## 결과물(있으면)

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] DDL이 변경되었을 경우 flyway 마이그레이션 스크립트를 작성하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #628

2024-04-11 10:55 UTC, ilyoil2 commented on jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
> +        Notice saveNotice = Notice.builder()
지금 그렇게 되어있는거 아닌가요?

2024-04-11 13:32 UTC, geunoo commented on jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
> +        Notice saveNotice = Notice.builder()
지금은 builder로 객체를 생성하고 그 객체를 저장, 그리고 그걸로 publish하고 있습니다.
이렇게되면 notice 객체의 id값이 null 이겠죠? db에 저장되어있지 않은 객체 상태니까

2024-04-11 13:32 UTC, geunoo commented on jobis-application/src/main/java/team/retum/jobis/domain/notice/usecase/CreateNoticeUseCase.java
> +        Notice saveNotice = Notice.builder()
@4mjeo

2024-04-12 08:03 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
> +                .putCustomData("detail_id", Optional.ofNullable(notification.getDetailId()).map(Object::toString).orElse(""))
여기도 바로 반환할 수 있지 않을까요?

2024-04-14 04:12 UTC, tedsoftj1123 reviewed
NoticeEventHandler에서 Notification객체 저장하는 코드도 추가해야될거같아요

2024-04-14 04:12 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
> +                .putCustomData("detail_id", Optional.ofNullable(notification.getDetailId()).map(Object::toString).orElse(""))
null이면 빈문자로 보내게바꾼이유가 뭔가요?

2024-04-14 08:50 UTC, 4mjeo commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
> +                .putCustomData("detail_id", Optional.ofNullable(notification.getDetailId()).map(Object::toString).orElse(""))
null 반환을 할 수 있다고 생각했는데 다시 수정하겠습니다.

2024-04-14 10:26 UTC, tedsoftj1123 approved these changes
rewrite한번 돌리고 sonarcloud issue난거 고쳐주세용 👍

2024-04-14 10:27 UTC, tedsoftj1123 requested changes

2024-04-14 10:27 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
> +            .putData("topic", notification.getDetailId().toString())
이거 detail_id로 해야되는거 아닌가요?

2024-04-14 13:04 UTC, 4mjeo commented on jobis-infrastructure/src/main/java/team/retum/jobis/thirdparty/fcm/FCMUtil.java
> +            .putData("topic", notification.getDetailId().toString())
아 수정하겠습니다

2024-04-14 23:37 UTC, tedsoftj1123 approved these changes

2024-04-15 00:03 UTC, merged