🔗 :: (#661) 모집의뢰서, 기업, 지원서 총 개수
Team-return/JOBIS-DSM-BE pull request #662
Opened 2024-05-10 10:25 UTC by 4mjeo

## 작업 내용 설명
- [ ] 모집의뢰서, 기업, 지원서 총 개수를 반환하는 api
- [ ] 

## 결과물(있으면)
![image](https://github.com/Team-return/JOBIS-DSM-BE/assets/129156398/0143638f-0e2e-4dce-be49-ac9df4759028)

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] DDL이 변경되었을 경우 flyway 마이그레이션 스크립트를 작성하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #661

2024-05-10 10:44 UTC, ilyoil2 commented on jobis-application/src/main/java/team/retum/jobis/domain/application/usecase/TeacherQueryApplicationsUseCase.java
> +        List<ApplicationVO> applicationVOS = queryApplicationPort.getAllByConditions(applicationFilter).stream()
VOs 로 바꿔주세요

2024-05-10 10:44 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
> +        @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy") Year year
Total 신청 개수 조회면 이 queryString은 필요 없지 않을까요?
![image](https://github.com/Team-return/JOBIS-DSM-BE/assets/127661235/0376a878-750e

2024-05-10 10:44 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/presentation/CompanyWebAdapter.java
> +    ) {
여기도

2024-05-10 10:44 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
> +        @RequestParam(value = "military_support", required = false) Boolean militarySupport
여기도

2024-05-10 10:44 UTC, ilyoil2 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
> +    @GetMapping("/count")
"/counts" 어떤가요?

2024-05-10 10:46 UTC, 4mjeo commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/recruitment/presentation/RecruitmentWebAdapter.java
> +    @GetMapping("/count")
별로인 것 같아요

2024-05-10 11:06 UTC, alsdl0629 requested changes
size 호출 대신 count 쿼리를 사용하는 게 좋을 것 같아요
그리고 데이터 개수를 가져오는 함수는 `countXXX` 이렇게 하는 건 어떤가요?

2024-05-11 03:54 UTC, 4mjeo commented
> size 호출 대신 count 쿼리를 사용하는 게 좋을 것 같아요 그리고 데이터 개수를 가져오는 함수는 `countXXX` 이렇게 하는 건 어떤가요?

수정하겠습니다

2024-05-11 04:39 UTC, alsdl0629 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/application/presentation/ApplicationWebAdapter.java
> +    public Long countApplications() {
다른 api와 동일하게 json으로 반환해주면 좋을 것 같아요

2024-05-11 07:47 UTC, alsdl0629 approved these changes

2024-05-11 07:52 UTC, merged