🔗 :: 기업 리스트 최근 의뢰년도로 수정
Team-return/JOBIS-DSM-BE pull request #673
Opened 2024-05-27 14:47 UTC by ilyoil2

## 작업 내용 설명
- [ ] .orderBy(companyEntity.recruitYear.desc()); 로 수정
- [ ] 

## 결과물(있으면)

## 체크리스트
- [ ] 어플리케이션 구동(혹은 테스트)시 오류는 없나요?
- [ ] DDL이 변경되었을 경우 flyway 마이그레이션 스크립트를 작성하였나요?
- [ ] 생성된 코드에 대한 테스트 코드가 작성 되었나요?

## 관련 이슈
- resolved #672

2024-05-27 23:44 UTC, geunoo approved these changes

2024-05-27 23:45 UTC, tedsoftj1123 commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
> +            .orderBy(companyEntity.recruitYear.desc());
company에 이런 필드 없지 않나요?

2024-05-27 23:45 UTC, geunoo commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
> +            .orderBy(companyEntity.recruitYear.desc());
그러네
너무 자연스럽다

2024-05-27 23:46 UTC, geunoo requested changes
.

2024-05-27 23:46 UTC, geunoo commented on jobis-infrastructure/src/main/java/team/retum/jobis/domain/company/persistence/CompanyPersistenceAdapter.java
> +            .orderBy(companyEntity.recruitYear.desc());
조인으로 최근 모집의뢰서 불러와서 그거 년도로 정렬해야될듯합니다

2024-05-28 10:48 UTC, 4mjeo approved these changes

2024-05-29 06:33 UTC, geunoo commented
테스트 해봤나요?

2024-05-29 14:22 UTC, ilyoil2 commented
네 해봤습니다

2024-05-30 02:48 UTC, geunoo approved these changes
@tedsoftj1123 가 approve 하면 머지합시다

2024-05-30 03:04 UTC, tedsoftj1123 approved these changes

2024-05-30 07:12 UTC, merged